PLUGIN_NAME=		usagereport
PLUGIN_VERSION=		1.0
PLUGIN_COMMENT=		Per-device internet usage report (NetFlow + DHCP device mapping)
PLUGIN_MAINTAINER=	ahmed_master23@hotmail.com
PLUGIN_WWW=		https://github.com/AhmedFelix/opnsense-usagereport

.include "../../Mk/plugins.mk"
